"""empty message

Revision ID: 27926b790456
Revises: 743b75c26801
Create Date: 2019-11-01 23:29:52.748572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27926b790456'
down_revision = '743b75c26801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
