"""empty message

Revision ID: 280dfd67f191
Revises: 4fbc5f10ad64
Create Date: 2019-11-15 19:06:57.943975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280dfd67f191'
down_revision = '4fbc5f10ad64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
