"""empty message

Revision ID: 284415c9d550
Revises: 280dfd67f191
Create Date: 2019-11-18 11:19:44.187584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284415c9d550'
down_revision = '280dfd67f191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
