"""task one to one relationship with sentence

Revision ID: 2bd8ebf89f93
Revises: e14fd00fb2b9
Create Date: 2019-10-28 16:29:31.074812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd8ebf89f93'
down_revision = 'e14fd00fb2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task', ['sentence_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='unique')
    # ### end Alembic commands ###
