"""add column modif to sentence

Revision ID: 2ef372a5977b
Revises: 104e69813dd6
Create Date: 2019-12-10 22:40:08.225885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef372a5977b'
down_revision = '104e69813dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modif', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.drop_column('modif')

    # ### end Alembic commands ###
