"""empty message

Revision ID: 4fbc5f10ad64
Revises: 2578da674dbf
Create Date: 2019-11-13 14:59:11.853477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbc5f10ad64'
down_revision = '2578da674dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queryTxt', sa.String(length=100), nullable=True))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('queryTxt')

    # ### end Alembic commands ###
