"""empty message

Revision ID: 743b75c26801
Revises: 2a05c8df2906
Create Date: 2019-11-01 23:14:53.289248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743b75c26801'
down_revision = '2a05c8df2906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
