"""empty message

Revision ID: 80ba78e56a5b
Revises: ec2fb1279b57
Create Date: 2021-02-10 11:11:21.349585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ba78e56a5b'
down_revision = 'ec2fb1279b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_task',
    sa.Column('s_task_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Enum('credible', 'noncredible', 'neutral/irrelevant', name='credrate_enum'), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Enum('slippery_slope', 'alleged_negative_consequences', 'twisting_word', 'hedging', name='tags_enum'), nullable=True),
    sa.Column('own_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('s_task_id'),
    sa.UniqueConstraint('sentence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_task')
    # ### end Alembic commands ###
