"""keywords string attribute added to article

Revision ID: 9f135cd1d24f
Revises: c7acd9844aa8
Create Date: 2019-11-06 15:13:42.557125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f135cd1d24f'
down_revision = 'c7acd9844aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
