"""article sentence task tables

Revision ID: e14fd00fb2b9
Revises: 
Create Date: 2019-10-28 16:25:46.006515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14fd00fb2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('access_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('query', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('sentence',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('sequence_nr', sa.Integer(), nullable=True),
    sa.Column('to_evaluate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Enum(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('article')
    # ### end Alembic commands ###
