"""empty message

Revision ID: ec2fb1279b57
Revises: 
Create Date: 2021-02-09 17:17:59.337704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2fb1279b57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('access_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('queryTxt', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('sentence',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('sequence_nr', sa.Integer(), nullable=True),
    sa.Column('to_evaluate', sa.Boolean(), nullable=True),
    sa.Column('modification', sa.String(length=20), nullable=True),
    sa.Column('modif', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    op.create_table('second_task',
    sa.Column('s_task_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Enum('credible', 'noncredible', 'neutral/irrelevant', name='credrate_enum'), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Enum('slippery_slope', 'alleged_negative_consequences', 'twisting_word', 'hedging', name='tags_enum'), nullable=True),
    sa.Column('own_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('s_task_id'),
    sa.UniqueConstraint('sentence_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Enum('CRED', 'NONCRED', 'NEU', name='credibilityrates'), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.sentence_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('sentence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('second_task')
    op.drop_table('sentence')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('article')
    # ### end Alembic commands ###
